//----------------------------------------
//
// Copyright © yanghy. All Rights Reserved.
//
// Licensed under Apache License 2.0
//
//----------------------------------------

package windows

import (
	"github.com/energye/lcl/lcl"
	"github.com/energye/lcl/types"

	wvTypes "github.com/energye/wv/types/windows"
)

type TDragDropEvent func(sender lcl.IObject, source lcl.IObject, X int32, Y int32)
type TDragOverEvent func(sender lcl.IObject, source lcl.IObject, X int32, Y int32, state types.TDragState, accept *bool)
type TEndDragEvent func(sender lcl.IObject, target lcl.IObject, X int32, Y int32)
type TLoaderBrowserProcessExitedEvent func(sender lcl.IObject, environment ICoreWebView2Environment, args ICoreWebView2BrowserProcessExitedEventArgs)
type TLoaderGetCustomSchemesEvent func(sender lcl.IObject, customSchemes *IWVCustomSchemeInfoArrayWrap)
type TLoaderNewBrowserVersionAvailableEvent func(sender lcl.IObject, environment ICoreWebView2Environment)
type TLoaderNotifyEvent func(sender lcl.IObject)
type TLoaderProcessInfosChangedEvent func(sender lcl.IObject, environment ICoreWebView2Environment)
type TNotifyEvent func(sender lcl.IObject)
type TOnAcceleratorKeyPressedEvent func(sender lcl.IObject, controller ICoreWebView2Controller, args ICoreWebView2AcceleratorKeyPressedEventArgs)
type TOnAddScriptToExecuteOnDocumentCreatedCompletedEvent func(sender lcl.IObject, errorCode types.HRESULT, result string)
type TOnBasicAuthenticationRequestedEvent func(sender lcl.IObject, webView ICoreWebView2, args ICoreWebView2BasicAuthenticationRequestedEventArgs)
type TOnBrowserExtensionEnableCompletedEvent func(sender lcl.IObject, errorCode types.HRESULT, extensionID string)
type TOnBrowserExtensionRemoveCompletedEvent func(sender lcl.IObject, errorCode types.HRESULT, extensionID string)
type TOnBrowserProcessExitedEvent func(sender lcl.IObject, environment ICoreWebView2Environment, args ICoreWebView2BrowserProcessExitedEventArgs)
type TOnBytesReceivedChangedEvent func(sender lcl.IObject, downloadOperation ICoreWebView2DownloadOperation, downloadID int32)
type TOnCallDevToolsProtocolMethodCompletedEvent func(sender lcl.IObject, errorCode types.HRESULT, result string, executionID int32)
type TOnCapturePreviewCompletedEvent func(sender lcl.IObject, errorCode types.HRESULT)
type TOnClearBrowsingDataCompletedEvent func(sender lcl.IObject, errorCode types.HRESULT)
type TOnClearCacheCompletedEvent func(sender lcl.IObject, result bool)
type TOnClearDataForOriginCompletedEvent func(sender lcl.IObject, result bool)
type TOnClientCertificateRequestedEvent func(sender lcl.IObject, webView ICoreWebView2, args ICoreWebView2ClientCertificateRequestedEventArgs)
type TOnCompMsgEvent func(sender lcl.IObject, message *types.TMessage, handled *bool)
type TOnContentLoadingEvent func(sender lcl.IObject, webView ICoreWebView2, args ICoreWebView2ContentLoadingEventArgs)
type TOnContextMenuRequestedEvent func(sender lcl.IObject, webView ICoreWebView2, args ICoreWebView2ContextMenuRequestedEventArgs)
type TOnCustomItemSelectedEvent func(sender lcl.IObject, menuItem ICoreWebView2ContextMenuItem)
type TOnDOMContentLoadedEvent func(sender lcl.IObject, webView ICoreWebView2, args ICoreWebView2DOMContentLoadedEventArgs)
type TOnDevToolsProtocolEventReceivedEvent func(sender lcl.IObject, webView ICoreWebView2, args ICoreWebView2DevToolsProtocolEventReceivedEventArgs, eventName string, eventID int32)
type TOnDownloadStartingEvent func(sender lcl.IObject, webView ICoreWebView2, args ICoreWebView2DownloadStartingEventArgs)
type TOnDownloadStateChangedEvent func(sender lcl.IObject, downloadOperation ICoreWebView2DownloadOperation, downloadID int32)
type TOnEstimatedEndTimeChangedEvent func(sender lcl.IObject, downloadOperation ICoreWebView2DownloadOperation, downloadID int32)
type TOnExecuteScriptCompletedEvent func(sender lcl.IObject, errorCode types.HRESULT, resultObjectAsJson string, executionID int32)
type TOnExecuteScriptWithResultCompletedEvent func(sender lcl.IObject, errorCode types.HRESULT, result ICoreWebView2ExecuteScriptResult, executionID int32)
type TOnFaviconChangedEvent func(sender lcl.IObject, webView ICoreWebView2, args lcl.IUnknown)
type TOnFrameContentLoadingEvent func(sender lcl.IObject, frame ICoreWebView2Frame, args ICoreWebView2ContentLoadingEventArgs, frameID uint32)
type TOnFrameCreatedEvent func(sender lcl.IObject, webView ICoreWebView2, args ICoreWebView2FrameCreatedEventArgs)
type TOnFrameDOMContentLoadedEvent func(sender lcl.IObject, frame ICoreWebView2Frame, args ICoreWebView2DOMContentLoadedEventArgs, frameID uint32)
type TOnFrameDestroyedEvent func(sender lcl.IObject, frame ICoreWebView2Frame, frameID uint32)
type TOnFrameNameChangedEvent func(sender lcl.IObject, frame ICoreWebView2Frame, frameID uint32)
type TOnFrameNavigationCompletedEvent func(sender lcl.IObject, frame ICoreWebView2Frame, args ICoreWebView2NavigationCompletedEventArgs, frameID uint32)
type TOnFrameNavigationStartingEvent func(sender lcl.IObject, frame ICoreWebView2Frame, args ICoreWebView2NavigationStartingEventArgs, frameID uint32)
type TOnFramePermissionRequestedEvent func(sender lcl.IObject, frame ICoreWebView2Frame, args ICoreWebView2PermissionRequestedEventArgs2, frameID uint32)
type TOnFrameScreenCaptureStartingEvent func(sender lcl.IObject, frame ICoreWebView2Frame, args ICoreWebView2ScreenCaptureStartingEventArgs, frameID uint32)
type TOnFrameWebMessageReceivedEvent func(sender lcl.IObject, frame ICoreWebView2Frame, args ICoreWebView2WebMessageReceivedEventArgs, frameID uint32)
type TOnGetCookiesCompletedEvent func(sender lcl.IObject, errorCode types.HRESULT, result ICoreWebView2CookieList)
type TOnGetCustomSchemesEvent func(sender lcl.IObject, customSchemes *IWVCustomSchemeInfoArrayWrap)
type TOnGetFaviconCompletedEvent func(sender lcl.IObject, errorCode types.HRESULT, result lcl.IStreamAdapter)
type TOnGetNonDefaultPermissionSettingsCompletedEvent func(sender lcl.IObject, errorCode types.HRESULT, result ICoreWebView2PermissionSettingCollectionView)
type TOnGetProcessExtendedInfosCompletedEvent func(sender lcl.IObject, errorCode types.HRESULT, result ICoreWebView2ProcessExtendedInfoCollection)
type TOnIgnoreCertificateErrorsCompletedEvent func(sender lcl.IObject, result bool)
type TOnInitializationErrorEvent func(sender lcl.IObject, errorCode types.HRESULT, errorMessage string)
type TOnIsDefaultDownloadDialogOpenChangedEvent func(sender lcl.IObject, webView ICoreWebView2)
type TOnIsDocumentPlayingAudioChangedEvent func(sender lcl.IObject, webView ICoreWebView2)
type TOnIsMutedChangedEvent func(sender lcl.IObject, webView ICoreWebView2)
type TOnLaunchingExternalUriSchemeEvent func(sender lcl.IObject, webView ICoreWebView2, args ICoreWebView2LaunchingExternalUriSchemeEventArgs)
type TOnMoveFocusRequestedEvent func(sender lcl.IObject, controller ICoreWebView2Controller, args ICoreWebView2MoveFocusRequestedEventArgs)
type TOnNavigationCompletedEvent func(sender lcl.IObject, webView ICoreWebView2, args ICoreWebView2NavigationCompletedEventArgs)
type TOnNavigationStartingEvent func(sender lcl.IObject, webView ICoreWebView2, args ICoreWebView2NavigationStartingEventArgs)
type TOnNewWindowRequestedEvent func(sender lcl.IObject, webView ICoreWebView2, args ICoreWebView2NewWindowRequestedEventArgs)
type TOnNonClientRegionChangedEvent func(sender lcl.IObject, controller ICoreWebView2CompositionController, args ICoreWebView2NonClientRegionChangedEventArgs)
type TOnNotificationCloseRequestedEvent func(sender lcl.IObject, notification ICoreWebView2Notification, args lcl.IUnknown)
type TOnNotificationReceivedEvent func(sender lcl.IObject, webView ICoreWebView2, args ICoreWebView2NotificationReceivedEventArgs)
type TOnOfflineCompletedEvent func(sender lcl.IObject, result bool)
type TOnPermissionRequestedEvent func(sender lcl.IObject, webView ICoreWebView2, args ICoreWebView2PermissionRequestedEventArgs)
type TOnPrintCompletedEvent func(sender lcl.IObject, errorCode types.HRESULT, result wvTypes.TWVPrintStatus)
type TOnPrintToPdfCompletedEvent func(sender lcl.IObject, errorCode types.HRESULT, result bool)
type TOnPrintToPdfStreamCompletedEvent func(sender lcl.IObject, errorCode types.HRESULT, result lcl.IStreamAdapter)
type TOnProcessFailedEvent func(sender lcl.IObject, webView ICoreWebView2, args ICoreWebView2ProcessFailedEventArgs)
type TOnProcessInfosChangedEvent func(sender lcl.IObject, environment ICoreWebView2Environment)
type TOnProfileAddBrowserExtensionCompletedEvent func(sender lcl.IObject, errorCode types.HRESULT, result ICoreWebView2BrowserExtension)
type TOnProfileDeletedEvent func(sender lcl.IObject, profile ICoreWebView2Profile)
type TOnProfileGetBrowserExtensionsCompletedEvent func(sender lcl.IObject, errorCode types.HRESULT, result ICoreWebView2BrowserExtensionList)
type TOnRefreshIgnoreCacheCompletedEvent func(sender lcl.IObject, errorCode types.HRESULT, resultObjectAsJson string)
type TOnRetrieveHTMLCompletedEvent func(sender lcl.IObject, result bool, hTML string)
type TOnRetrieveMHTMLCompletedEvent func(sender lcl.IObject, result bool, mHTML string)
type TOnRetrieveTextCompletedEvent func(sender lcl.IObject, result bool, text string)
type TOnSaveAsUIShowingEvent func(sender lcl.IObject, webView ICoreWebView2, args ICoreWebView2SaveAsUIShowingEventArgs)
type TOnSaveFileSecurityCheckStartingEvent func(sender lcl.IObject, webView ICoreWebView2, args ICoreWebView2SaveFileSecurityCheckStartingEventArgs)
type TOnScreenCaptureStartingEvent func(sender lcl.IObject, webView ICoreWebView2, args ICoreWebView2ScreenCaptureStartingEventArgs)
type TOnScriptDialogOpeningEvent func(sender lcl.IObject, webView ICoreWebView2, args ICoreWebView2ScriptDialogOpeningEventArgs)
type TOnServerCertificateErrorActionsCompletedEvent func(sender lcl.IObject, errorCode types.HRESULT)
type TOnServerCertificateErrorDetectedEvent func(sender lcl.IObject, webView ICoreWebView2, args ICoreWebView2ServerCertificateErrorDetectedEventArgs)
type TOnSetPermissionStateCompletedEvent func(sender lcl.IObject, errorCode types.HRESULT)
type TOnShowSaveAsUICompletedEvent func(sender lcl.IObject, errorCode types.HRESULT, result wvTypes.TWVSaveAsUIResult)
type TOnSimulateKeyEventCompletedEvent func(sender lcl.IObject, result bool)
type TOnSourceChangedEvent func(sender lcl.IObject, webView ICoreWebView2, args ICoreWebView2SourceChangedEventArgs)
type TOnStatusBarTextChangedEvent func(sender lcl.IObject, webView ICoreWebView2)
type TOnTrySuspendCompletedEvent func(sender lcl.IObject, errorCode types.HRESULT, result bool)
type TOnWebMessageReceivedEvent func(sender lcl.IObject, webView ICoreWebView2, args ICoreWebView2WebMessageReceivedEventArgs)
type TOnWebResourceRequestedEvent func(sender lcl.IObject, webView ICoreWebView2, args ICoreWebView2WebResourceRequestedEventArgs)
type TOnWebResourceResponseReceivedEvent func(sender lcl.IObject, webView ICoreWebView2, args ICoreWebView2WebResourceResponseReceivedEventArgs)
type TOnWebResourceResponseViewGetContentCompletedEvent func(sender lcl.IObject, errorCode types.HRESULT, result lcl.IStreamAdapter, resourceID int32)
type TStartDragEvent func(sender lcl.IObject, dragObject *lcl.IDragObject)
