//----------------------------------------
//
// Copyright © yanghy. All Rights Reserved.
//
// Licensed under Apache License 2.0
//
//----------------------------------------

package linux

// JSCCheckSyntaxMode ENUM
type JSCCheckSyntaxMode = int32

const (
	JSC_CHECK_SYNTAX_MODE_SCRIPT JSCCheckSyntaxMode = iota
	JSC_CHECK_SYNTAX_MODE_MODULE
)

// JSCCheckSyntaxResult ENUM
type JSCCheckSyntaxResult = int32

const (
	JSC_CHECK_SYNTAX_RESULT_SUCCESS JSCCheckSyntaxResult = iota
	JSC_CHECK_SYNTAX_RESULT_RECOVERABLE_ERROR
	JSC_CHECK_SYNTAX_RESULT_IRRECOVERABLE_ERROR
	JSC_CHECK_SYNTAX_RESULT_UNTERMINATED_LITERAL_ERROR
	JSC_CHECK_SYNTAX_RESULT_OUT_OF_MEMORY_ERROR
	JSC_CHECK_SYNTAX_RESULT_STACK_OVERFLOW_ERROR
)

// JSCTypedArrayType ENUM
type JSCTypedArrayType = int32

const (
	JSC_TYPED_ARRAY_NONE JSCTypedArrayType = iota
	JSC_TYPED_ARRAY_INT8
	JSC_TYPED_ARRAY_INT16
	JSC_TYPED_ARRAY_INT32
	JSC_TYPED_ARRAY_INT64
	JSC_TYPED_ARRAY_UINT8
	JSC_TYPED_ARRAY_UINT8_CLAMPED
	JSC_TYPED_ARRAY_UINT16
	JSC_TYPED_ARRAY_UINT32
	JSC_TYPED_ARRAY_UINT64
	JSC_TYPED_ARRAY_FLOAT32
	JSC_TYPED_ARRAY_FLOAT64
)

// JSCValuePropertyFlags ENUM
type JSCValuePropertyFlags = int32

const (
	JSC_VALUE_PROPERTY_CONFIGURABLE JSCValuePropertyFlags = 1 << 0
	JSC_VALUE_PROPERTY_ENUMERABLE                         = 1 << 1
	JSC_VALUE_PROPERTY_WRITABLE                           = 1 << 2
)

// JSType ENUM
type JSType = int32

const (
	KJSTypeUndefined JSType = iota
	KJSTypeNull
	KJSTypeBoolean
	KJSTypeNumber
	KJSTypeString
	KJSTypeObject
)

// TSoupDateFormat ENUM
type TSoupDateFormat = int32

const (
	SOUP_DATE_HTTP            TSoupDateFormat = 1
	SOUP_DATE_COOKIE                          = 2
	SOUP_DATE_RFC2822                         = 3
	SOUP_DATE_ISO8601_COMPACT                 = 4
	SOUP_DATE_ISO8601_FULL                    = 5
	SOUP_DATE_ISO8601                         = 5
	SOUP_DATE_ISO8601_XMLRPC                  = 6
)

// TSoupMessageHeadersType ENUM
type TSoupMessageHeadersType = int32

const (
	SOUP_MESSAGE_HEADERS_REQUEST TSoupMessageHeadersType = iota
	SOUP_MESSAGE_HEADERS_RESPONSE
	SOUP_MESSAGE_HEADERS_MULTIPART
)

// TWebkit2Version ENUM
type TWebkit2Version = int32

const (
	Wkv4_0 TWebkit2Version = iota
	Wkv4_1
)

// TWkProcessId ENUM
type TWkProcessId = int32

const (
	WkPID_BROWSER TWkProcessId = iota
	WkPID_RENDER
)

// JSType ENUM Rename: uWkJSValue.JSType
type UWJSValueJSType = int32

const (
	JtInvalid UWJSValueJSType = iota
	JtNotSupported
	JtUndefined
	JtNull
	JtString
	JtNumber
	JtInteger
	JtBoolean
	JtException
)

// WebKitAutoplayPolicy ENUM
//
//	用于指定自动播放策略的值
type WebKitAutoplayPolicy = int32

const (
	WEBKIT_AUTOPLAY_ALLOW WebKitAutoplayPolicy = iota
	WEBKIT_AUTOPLAY_ALLOW_WITHOUT_SOUND
	WEBKIT_AUTOPLAY_DENY
)

// WebKitCacheModel ENUM
//
//	用于确定#WebKitWebContext缓存模型的值
type WebKitCacheModel = int32

const (
	WEBKIT_CACHE_MODEL_DOCUMENT_VIEWER WebKitCacheModel = iota
	WEBKIT_CACHE_MODEL_WEB_BROWSER
	WEBKIT_CACHE_MODEL_DOCUMENT_BROWSER
)

// WebKitContextMenuAction ENUM
type WebKitContextMenuAction = int32

const (
	WEBKIT_CONTEXT_MENU_ACTION_NO_ACTION WebKitContextMenuAction = iota
	WEBKIT_CONTEXT_MENU_ACTION_OPEN_LINK
	WEBKIT_CONTEXT_MENU_ACTION_OPEN_LINK_IN_NEW_WINDOW
	WEBKIT_CONTEXT_MENU_ACTION_DOWNLOAD_LINK_TO_DISK
	WEBKIT_CONTEXT_MENU_ACTION_COPY_LINK_TO_CLIPBOARD
	WEBKIT_CONTEXT_MENU_ACTION_OPEN_IMAGE_IN_NEW_WINDOW
	WEBKIT_CONTEXT_MENU_ACTION_DOWNLOAD_IMAGE_TO_DISK
	WEBKIT_CONTEXT_MENU_ACTION_COPY_IMAGE_TO_CLIPBOARD
	WEBKIT_CONTEXT_MENU_ACTION_COPY_IMAGE_URL_TO_CLIPBOARD
	WEBKIT_CONTEXT_MENU_ACTION_OPEN_FRAME_IN_NEW_WINDOW
	WEBKIT_CONTEXT_MENU_ACTION_GO_BACK
	WEBKIT_CONTEXT_MENU_ACTION_GO_FORWARD
	WEBKIT_CONTEXT_MENU_ACTION_STOP
	WEBKIT_CONTEXT_MENU_ACTION_RELOAD
	WEBKIT_CONTEXT_MENU_ACTION_COPY
	WEBKIT_CONTEXT_MENU_ACTION_CUT
	WEBKIT_CONTEXT_MENU_ACTION_PASTE
	WEBKIT_CONTEXT_MENU_ACTION_DELETE
	WEBKIT_CONTEXT_MENU_ACTION_SELECT_ALL
	WEBKIT_CONTEXT_MENU_ACTION_INPUT_METHODS
	WEBKIT_CONTEXT_MENU_ACTION_UNICODE
	WEBKIT_CONTEXT_MENU_ACTION_SPELLING_GUESS
	WEBKIT_CONTEXT_MENU_ACTION_NO_GUESSES_FOUND
	WEBKIT_CONTEXT_MENU_ACTION_IGNORE_SPELLING
	WEBKIT_CONTEXT_MENU_ACTION_LEARN_SPELLING
	WEBKIT_CONTEXT_MENU_ACTION_IGNORE_GRAMMAR
	WEBKIT_CONTEXT_MENU_ACTION_FONT_MENU
	WEBKIT_CONTEXT_MENU_ACTION_BOLD
	WEBKIT_CONTEXT_MENU_ACTION_ITALIC
	WEBKIT_CONTEXT_MENU_ACTION_UNDERLINE
	WEBKIT_CONTEXT_MENU_ACTION_OUTLINE
	WEBKIT_CONTEXT_MENU_ACTION_INSPECT_ELEMENT
	WEBKIT_CONTEXT_MENU_ACTION_OPEN_VIDEO_IN_NEW_WINDOW
	WEBKIT_CONTEXT_MENU_ACTION_OPEN_AUDIO_IN_NEW_WINDOW
	WEBKIT_CONTEXT_MENU_ACTION_COPY_VIDEO_LINK_TO_CLIPBOARD
	WEBKIT_CONTEXT_MENU_ACTION_COPY_AUDIO_LINK_TO_CLIPBOARD
	WEBKIT_CONTEXT_MENU_ACTION_TOGGLE_MEDIA_CONTROLS
	WEBKIT_CONTEXT_MENU_ACTION_TOGGLE_MEDIA_LOOP
	WEBKIT_CONTEXT_MENU_ACTION_ENTER_VIDEO_FULLSCREEN
	WEBKIT_CONTEXT_MENU_ACTION_MEDIA_PLAY
	WEBKIT_CONTEXT_MENU_ACTION_MEDIA_PAUSE
	WEBKIT_CONTEXT_MENU_ACTION_MEDIA_MUTE
	WEBKIT_CONTEXT_MENU_ACTION_DOWNLOAD_VIDEO_TO_DISK
	WEBKIT_CONTEXT_MENU_ACTION_DOWNLOAD_AUDIO_TO_DISK
	WEBKIT_CONTEXT_MENU_ACTION_INSERT_EMOJI
	WEBKIT_CONTEXT_MENU_ACTION_PASTE_AS_PLAIN_TEXT
	WEBKIT_CONTEXT_MENU_ACTION_CUSTOM = 10000
)

// WebKitCookieAcceptPolicy ENUM
//
//	用于表示cookie接受策略的值。
type WebKitCookieAcceptPolicy = int32

const (
	WEBKIT_COOKIE_POLICY_ACCEPT_ALWAYS WebKitCookieAcceptPolicy = iota
	WEBKIT_COOKIE_POLICY_ACCEPT_NEVER
	WEBKIT_COOKIE_POLICY_ACCEPT_NO_THIRD_PARTY
)

// WebKitCookiePersistentStorage ENUM
//
//	用于表示cookie持久存储类型的值。
type WebKitCookiePersistentStorage = int32

const (
	WEBKIT_COOKIE_PERSISTENT_STORAGE_TEXT WebKitCookiePersistentStorage = iota
	WEBKIT_COOKIE_PERSISTENT_STORAGE_SQLITE
)

// WebKitHardwareAccelerationPolicy ENUM
//
//	用于确定硬件加速策略的值
type WebKitHardwareAccelerationPolicy = int32

const (
	WEBKIT_HARDWARE_ACCELERATION_POLICY_ON_DEMAND WebKitHardwareAccelerationPolicy = iota
	WEBKIT_HARDWARE_ACCELERATION_POLICY_ALWAYS
	WEBKIT_HARDWARE_ACCELERATION_POLICY_NEVER
)

// WebKitLoadEvent ENUM
//
//	值用于表示在#WebKitWebView加载操作期间发生的不同事件。
type WebKitLoadEvent = int32

const (
	WEBKIT_LOAD_STARTED WebKitLoadEvent = iota
	WEBKIT_LOAD_REDIRECTED
	WEBKIT_LOAD_COMMITTED
	WEBKIT_LOAD_FINISHED
)

// WebKitPolicyDecisionType ENUM
//
//	用于确定期间的策略决策类型的值
type WebKitPolicyDecisionType = int32

const (
	WEBKIT_POLICY_DECISION_TYPE_NAVIGATION_ACTION WebKitPolicyDecisionType = iota
	WEBKIT_POLICY_DECISION_TYPE_NEW_WINDOW_ACTION
	WEBKIT_POLICY_DECISION_TYPE_RESPONSE
)

// WebKitUserContentInjectedFrames ENUM
//
//	指定要在哪些框架中插入用户样式表。
type WebKitUserContentInjectedFrames = int32

const (
	WEBKIT_USER_CONTENT_INJECT_ALL_FRAMES WebKitUserContentInjectedFrames = iota
	WEBKIT_USER_CONTENT_INJECT_TOP_FRAME
)

// WebKitUserScriptInjectionTime ENUM
//
//	指定将在文档的哪个位置插入用户脚本。
type WebKitUserScriptInjectionTime = int32

const (
	WEBKIT_USER_SCRIPT_INJECT_AT_DOCUMENT_START WebKitUserScriptInjectionTime = iota
	WEBKIT_USER_SCRIPT_INJECT_AT_DOCUMENT_END
)

// WebKitUserStyleLevel ENUM
//
//	指定如何处理用户样式表。
type WebKitUserStyleLevel = int32

const (
	WEBKIT_USER_STYLE_LEVEL_USER WebKitUserStyleLevel = iota
	WEBKIT_USER_STYLE_LEVEL_AUTHOR
)

// WebKitWebProcessTerminationReason ENUM
//
//	用于指定web进程异常终止原因的值
type WebKitWebProcessTerminationReason = int32

const (
	WEBKIT_WEB_PROCESS_CRASHED WebKitWebProcessTerminationReason = iota
	WEBKIT_WEB_PROCESS_EXCEEDED_MEMORY_LIMIT
	WEBKIT_WEB_PROCESS_TERMINATED_BY_API
)
